### ISSUE TITLE
Submitting a list of IDs to order

### ISSUE THREAD

**Issue by ECCCBen** [m9brady/eodms-api-client#1]
Submitted:

`eodms -c Radarsat2 --record-ids ListOfIdsToDownload.txt --dump-results`

Received this:

```
2021-02-12 10:47:52 | eodmsapi.cli | INFO | Fast-ordering for 54 record(s)
2021-02-12 10:47:52 | eodmsapi.main | INFO | Submitting order for 1 item
2021-02-12 10:47:52 | eodmsapi.cli | INFO | EODMS Order Ids for tracking progress: ['229386']
Traceback (most recent call last):
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Continuum\anaconda3\envs\tf2\Scripts\eodms.exe\__main__.py", line 7, in <module>
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\username\appdata\local\continuum\anaconda3\envs\tf2\lib\site-packages\eodms_api_client\cli.py", line 257, in cli
    's' if n_results != 1 else '',
UnboundLocalError: local variable 'n_results' referenced before assignment
```

Still got an email from EODMS saying they are preparing my order for the file ListOfIdsToDownload.txt
[ListOfIdsToDownload.txt](https://github.com/m9brady/eodms-api-client/files/5972938/ListOfIdsToDownload.txt)

**Comment by m9brady** [comment]
Thanks for testing RS2 Ben!
I uploaded a new build to pypi that I was able to get working without having to split up your `ListOfIdsToDownload.txt` 👍

**Comment by m9brady** [comment]
Closing as I think we solved your issue. Feel free to re-open if you're still having problems!
